117 favorite pins
fga-eps-mds/2020.1-stay-safe-front-end pull request #122
Opened 2020-12-10 20:26 UTC by danieldagerom

## Issue 
Resolves #117 

## Description
Like the occurrences pins is shown on the map, the map also render pins of the user favorite places, the difference is that this pin icon/image looks like a star.

## Screenshots:
![photo5084923326786283675](https://user-images.githubusercontent.com/42456421/101825375-4a78a900-3b0c-11eb-96ca-6756ba61b869.jpg)
![photo5084923326786283676](https://user-images.githubusercontent.com/42456421/101825388-4e0c3000-3b0c-11eb-9851-f0217b6a0316.jpg)
## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

## How to validate?

Register a favorite place, then in the favorite places screen, after clicking on one card, it will render a pin of the favorite place created, within a static map.

2020-12-12 18:34 UTC, rossicler requested changes, later dismissed

2020-12-12 18:34 UTC, rossicler commented on src/components/FavoriteMarker/index.tsx
> +            onPress={() => console.log(favoriteplace.name)}
Is this necessary? console.log is used only as a debugger.

2020-12-13 00:12 UTC, silvasara approved these changes

2020-12-13 02:05 UTC, renan601 approved these changes

2020-12-13 02:06 UTC, merged