Translated some fields from English to Portuguese, improved some text…
fga-eps-mds/2020.1-stay-safe-front-end pull request #88
Opened 2020-11-20 22:25 UTC by LuizPettengill

…s, changed ammount of zoom on DF map

## Issue 
Resolves #

## Description

## Screenshots (if appropriate):

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

## Known problems (if appropriate):

## How to validate?

2020-11-21 23:55 UTC, silvasara requested changes
- In the login screen the language is not yet standardized, change from Username to "Usuário" or "Nome de usuário":

![image](https://user-images.githubusercontent.com/30883179/99890177-596de900-2c3b-11eb-8cbe-0fa9ab9742c6.png)

- The DF map is still far away, it should be zoomed in:
![image](https://user-images.githubusercontent.com/30883179/99890223-cf725000-2c3b-11eb-8acb-960e11c7317a.png)

2020-11-21 23:55 UTC, silvasara commented on src/screens/Home/index.tsx
> +    const finalDate = "12/2020";
These values ​​must not be static, they must be the ones being passed in the request to the backend

2020-11-23 20:32 UTC, silvasara commented on src/screens/Home/index.tsx
> +    const finalDate = "12/2020";
Disregard this comment, I was wrong

2020-11-28 01:06 UTC, silvasara approved these changes

2020-11-30 00:58 UTC, renan601 approved these changes

2020-11-30 00:59 UTC, merged